### ISSUE TITLE
OnnxRuntime Error : sequential_executor.cc:318 Execute] Non-zero status code returned while running Transpose node. && GPU Usage Issue

### ISSUE THREAD

**Issue by JunHyunjae** [onnx/tensorflow-onnx#1606]
**Error Message **
2021-07-09 02:08:35.365931341 [E:onnxruntime:, sequential_executor.cc:318 Execute] Non-zero status code returned while running Transpose node. Name:'StatefulPartitionedCall/EfficientDet-D0/bifpn/node_05/1_dn_lvl_3/input_0_up_lvl_3/1x1_pre_sample/batchnorm/FusedBatchNormV3__1010' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument
Traceback (most recent call last):
  File "tfmodelTest.py", line 13, in <module>
    results_ort = sess.run(["num_detections", "detection_boxes", "detection_classes","detection_scores"], {"input_tensor": input1})
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 123, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Transpose node. Name:'StatefulPartitionedCall/EfficientDet-D0/bifpn/node_05/1_dn_lvl_3/input_0_up_lvl_3/1x1_pre_sample/batchnorm/FusedBatchNormV3__1010' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument

**1. Used model** : https://tfhub.dev/tensorflow/efficientdet/d0/1

**2. Used Command** : python -m tf2onnx.convert --saved-model ./ --output model.onnx

**3. Environment**
Cython                 0.29.23
numpy                  1.19.1
onnx                   1.7.0
onnxruntime-gpu        1.5.2
pycuda                 2019.1.2
tensorflow-gpu         2.2.0
tf2onnx                1.10.0
torch                  1.7.1
torch2trt              0.2.0

**4. Test Code**
import onnxruntime as ort
import numpy as np

input1 = np.ones((1, 100, 100, 3), np.uint8)
sess = ort.InferenceSession("model.onnx")
results_ort = sess.run(["num_detections", "detection_boxes", "detection_classes","detection_scores"], {"input_tensor": input1})

I did only the basics, but an error occurred and I can't figure it out.
Any help would be appreciated.

**Comment by JunHyunjae** [comment]
I solved it by using tensorrt provider. :)

**Comment by JunHyunjae** [comment]
sess = ort.InferenceSession(model_path, providers=["TensorrtExecutionProvider"])
sess = ort.InferenceSession(model_path, providers=["CPUExecutionProvider"])

Neither of the above causes an error, but it seems that the GPU is not used at all.

I monitored it with nvidia-smi, but the GPU usage is not increasing at all.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @JunHyunjae, thanks for the thorough investigation.  Since the model works on TensorRT and on the CPU provider, I don't think it is a problem with the converter.  Can you please open an issue with onnxruntime?  Please include the converted onnx model.  https://github.com/microsoft/onnxruntime

**Comment by JunHyunjae** [comment]
Hi @TomWildenhain-Microsoft 
I created an issue on the onnxruntime issue board :)

https://github.com/microsoft/onnxruntime/issues/8352

**Comment by hariharans29** [comment]
This has been fixed in ORT 1.8

**Comment by guschmue** [comment]
super, thanks!
